In [1]:
v = [1, 3, 4, 2, 1, 1, 0, -1]

8-element Vector{Int64}:
  1
  3
  4
  2
  1
  1
  0
 -1

In [2]:
sort!(v)

8-element Vector{Int64}:
 -1
  0
  1
  1
  1
  2
  3
  4

In [3]:
f = A -> A ^2

#1 (generic function with 1 method)

In [4]:
A = rand(1:4, 3, 3)

3×3 Matrix{Int64}:
 4  3  1
 1  1  1
 3  2  2

In [5]:
f(A)

3×3 Matrix{Int64}:
 22  17  9
  8   6  4
 20  15  9

In [6]:
f.(A)

3×3 Matrix{Int64}:
 16  9  1
  1  1  1
  9  4  4

In [7]:
B = A

3×3 Matrix{Int64}:
 4  3  1
 1  1  1
 3  2  2

In [8]:
C = copy(A)

3×3 Matrix{Int64}:
 4  3  1
 1  1  1
 3  2  2

In [9]:
[ B C ]

3×6 Matrix{Int64}:
 4  3  1  4  3  1
 1  1  1  1  1  1
 3  2  2  3  2  2

In [10]:
A[1] = 17

17

In [11]:
C

3×3 Matrix{Int64}:
 4  3  1
 1  1  1
 3  2  2

In [12]:
B

3×3 Matrix{Int64}:
 17  3  1
  1  1  1
  3  2  2

In [13]:
x = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [14]:
x'

1×3 adjoint(::Vector{Float64}) with eltype Float64:
 1.0  1.0  1.0

In [15]:
b = A * x

3-element Vector{Float64}:
 21.0
  3.0
  7.0

In [16]:
Asym = A + A'

3×3 Matrix{Int64}:
 34  4  4
  4  2  3
  4  3  4

In [17]:
Apd = A'A

3×3 Matrix{Int64}:
 299  58  24
  58  14   8
  24   8   6

In [18]:
A\b

3-element Vector{Float64}:
 1.0000000000000004
 0.9999999999999966
 1.0000000000000029